### PR TITLE
Add emote parsing.

### PR DESCRIPTION
**Pull request by jeppevinkel**
Made an emote interface and emote parsing to make it easier to use emotes in the future.
It sorts the emote array so emotes are stored in order of appearance in the message.

```ts
interface ITwitchEmote {
    id: string,
    start: number,
    end: number
}
```

### CODE REVIEW

**Comment by BOLL7708** [comment]
I will not be working on this for another week or so, but will take a look at this when that happens.

**Comment by jeppevinkel** [comment]
That's fine. I'm not using it myself so not really affecting me 😛

**Comment by jeppevinkel** [comment]
Beware. Another commit has sneaked its way in here.

**Comment by BOLL7708** [comment]
I will need to figure out how to pull this into a separate branch so I can inspect/test it while avoiding disruption...

**Pull request merged**
